Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gdf2.to_csv("output/po_kontinentima.csv")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/j1/q1_l0vfs66zfhnv67vv0bp700000gq/T/ipykernel_4871/902970223.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgdf2[0m[0;34m.[0m[0mto_csv[0m[0;34m([0m[0;34m"output/po_kontinentima.csv"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py[0m in [0;36mto_csv[0;34m(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)[0m
[1;32m   3464[0m         )
[1;32m   3465[0m [0;34m[0m[0m
[0;32m-> 3466[0;31m         return DataFrameRenderer(formatter).to_csv(
[0m[1;32m   3467[0m             [0mpath_or_buf[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3468[0m             [0mline_terminator[0m[0;34m=[0m[0mline_terminator[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py[0m in [0;36mto_csv[0;34m(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)[0m
[1;32m   1103[0m             [0mformatter[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mfmt[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1104[0m         )
[0;32m-> 1105[0;31m         [0mcsv_formatter[0m[0;34m.[0m[0msave[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1106[0m [0;34m[0m[0m
[1;32m   1107[0m         [0;32mif[0m [0mcreated_buffer[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py[0m in [0;36msave[0;34m(self)[0m
[1;32m    235[0m         """
[1;32m    236[0m         [0;31m# apply compression and byte/text conversion[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 237[0;31m         with get_handle(
[0m[1;32m    238[0m             [0mself[0m[0;34m.[0m[0mfilepath_or_buffer[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    239[0m             [0mself[0m[0;34m.[0m[0mmode[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.9/site-packages/pandas/io/common.py[0m in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    700[0m         [0;32mif[0m [0mioargs[0m[0;34m.[0m[0mencoding[0m [0;32mand[0m [0;34m"b"[0m [0;32mnot[0m [0;32min[0m [0mioargs[0m[0;34m.[0m[0mmode[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    701[0m             [0;31m# Encoding[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 702[0;31m             handle = open(
[0m[1;32m    703[0m                 [0mhandle[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    704[0m                 [0mioargs[0m[0;34m.[0m[0mmode[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'output/po_kontinentima.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'output/po_kontinentima.csv'

